// QoRders/frontend-react/src/components/Layout/Footer/Footer.jsx
import React from 'react';
import './Footer.css';

const Footer = () => {
    return (
        <div className="footer">
            <div className="footer-content">
                <p>&copy; 2025 QoRders</p>
            </div>
            <div className="footer-links">
                {/* <a href="https://github.com/AngeletaT" target="_blank" rel="noopener noreferrer">Àngela Torró</a> */}
                <a href="https://github.com/CainMartinez" target="_blank" rel="noopener noreferrer">
                    <svg 
                        className="github-icon" 
                        height="20" 
                        width="20" 
                        viewBox="0 0 16 16" 
                        aria-hidden="true"
                    >
                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" fill="currentColor"></path>
                    </svg>&nbsp;&nbsp;
                    Caín Martínez Bernabeu
                </a>
                {/* <a href="https://github.com/AlvaroGarCam" target="_blank" rel="noopener noreferrer">Álvaro Garrido</a> */}
            </div>
        </div>
    );
};

export default Footer;

// QoRders/frontend-vue/src/layouts/Footer.vue
<template>
  <div class="footer">
    <div class="footer-content">
      <p>&copy; 2025 QoRders</p>
    </div>
    <div class="footer-links">
      <!-- <a href="https://github.com/AngeletaT">Àngela Torró </a> -->
      <a href="https://github.com/CainMartinez" target="_blank" rel="noopener noreferrer" class="github-link">
        <svg 
            class="github-icon" 
            height="20" 
            width="20" 
            viewBox="0 0 16 16" 
            aria-hidden="true"
        >
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" fill="currentColor"></path>
        </svg>
        <span>Caín Martínez Bernabeu</span>
      </a>
      <!-- <a href="https://github.com/AlvaroGarCam">Álvaro Garrido </a> -->
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
</script>

<style scoped>
.footer {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 10px 20px;
  background-color: #f3f3f3;
  box-shadow: 0 -4px 8px rgba(0, 0, 0, 0.1);
  color: #333;
}

.footer-content {
  margin-bottom: 10px;
}

.footer-links {
  display: flex;
  gap: 15px;
  justify-content: center;
  flex-wrap: wrap;
}

p {
  color: #495057;
  margin: 0;
}

a {
  color: #495057;
  text-decoration: none;
  padding: 6px 12px;
  border-radius: 4px;
  transition: all 0.3s ease;
  /* Quitamos el fondo por defecto */
  background-color: transparent;
}

a:hover {
  background-color: rgba(233, 236, 239, 0.7);
  color: #333;
  transform: translateY(-2px);
}

.github-link {
  display: flex;
  align-items: center;
  gap: 6px;
}

.github-icon {
  margin-right: 2px;
  transition: transform 0.3s ease;
}

.github-link:hover .github-icon {
  transform: scale(1.1) rotate(5deg);
}

@media (max-width: 480px) {
  .footer {
    padding: 10px;
  }
  
  .footer-links {
    flex-direction: column;
    align-items: center;
  }
}
</style>
